name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - main
      - dev

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r test-requirements.txt

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results --maxfail=5 --disable-warnings || true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results
          subfolder: ${{ github.ref_name }}

      - name: Replace run numbers on GitHub Pagesindex.html
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            sed -i "s/MAIN_RUN_NUMBER_PLACEHOLDER/${{ github.run_number }}/g" gh-pages/index.html
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            sed -i "s/MAIN_RUN_NUMBER_PLACEHOLDER/0/g" gh-pages/index.html
          fi

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
