name: Run Tests and Generate Allure Report

on:
  push:
    branches:
      - "**"  # Runs on all branches

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r test-requirements.txt

      - name: Run tests and generate Allure results
        run: |
          pytest --alluredir=allure-results --maxfail=5 --disable-warnings || true

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Determine test status
        run: |
          STATUS_FILE="gh-pages/allure-history/${{ github.ref_name }}/latest/widgets/summary.json"
          STATUS_PATH="gh-pages/allure-history/${{ github.ref_name }}/status.txt"

          if [ -f "$STATUS_FILE" ]; then
            FAILED_TESTS=$(jq -r '.statistic.failed' "$STATUS_FILE")
            if [ "$FAILED_TESTS" -eq "0" ]; then
              echo "✅ Passed" > "$STATUS_PATH"
            else
              echo "❌ Failed" > "$STATUS_PATH"
            fi
          else
            echo "⚠️ No Results" > "$STATUS_PATH"
          fi

      - name: Update main index.html
        run: |
          echo "<html><body><h1>Branch Test Status</h1><ul>" > gh-pages/index.html
          for branch in $(ls gh-pages/allure-history); do
            STATUS=$(cat gh-pages/allure-history/$branch/status.txt || echo "⚠️ Unknown")
            echo "<li><a href='allure-history/$branch/latest/index.html'>$branch</a> - $STATUS</li>" >> gh-pages/index.html
          done
          echo "</ul></body></html>" >> gh-pages/index.html

      - name: Commit & Push Changes
        run: |
          cd gh-pages
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update test reports for ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin gh-pages
